OdeToFood/Models/CuisineType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Models
{
    public enum CuisineType
    {
        None,
        Italien,
        French,
        Danish
    }
}

OdeToFood/Models/ErrorMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Models
{
    public class ErrorMessage
    {
        public int id { get; set; }
        public String message { get; set; }
    }
}

OdeToFood/Models/Resturant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using OdeToFood.Models;

namespace OdeToFood.Models
{
    public class Resturant
    {
        public int Id { get; set; }

        [Display(Name="Resturant name")]
        [Required, MaxLength(12)]
        public String Name{ get; set; }
        public CuisineType Cuisine { get; set; }
    }
    
}

OdeToFood/ViewModels/ErrorViewModel.cs
using OdeToFood.Models;

namespace OdeToFood.ViewModels
{
    public class ErrorViewModel 
    {
        public Resturant Resturant { get; set; }
    }
}

OdeToFood/ViewModels/HomeIndexViewModel.cs
using OdeToFood.Models;
using System.Collections.Generic;

namespace OdeToFood.ViewModels
{
    public class HomeIndexViewModel
    {
        public IEnumerable<Resturant> Resturants { get; set; }
        public Resturant Resturant { get; set; }
        public string CurrentMessage { get; set; }
    }
}

OdeToFood/ViewModels/ResturantEditModel.cs
using OdeToFood.Models;
using System;
using System.ComponentModel.DataAnnotations;

namespace OdeToFood.ViewModels
{
    public class ResturantEditModel
    {
        [Required, MaxLength(80)]
        public String Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

OdeToFood/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace OdeToFood.Controllers
{
    [Route("[controller]/[action]")]
    public class AboutController
    {
        //[Route("")]
        public string Phone()
        {
            return "26250213";
        }
        //[Route("address")]
        public string Address()
        {
            return "Helgesensgade";
        }
    }
}

OdeToFood/Controllers/HomeController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Models;
using OdeToFood.Services;
using OdeToFood.ViewModels;

namespace OdeToFood.Controllers
{
    public class HomeController : Controller
    {
        private IResturantData _resturantData;
        private IErrorMessageData _errorMessage;
        private String _greeter;

        public HomeController(IResturantData resturantData
                             ,IGreeter greeter
                             ,IErrorMessageData errorMessage)
        {
            _resturantData = resturantData;
            _greeter = greeter.GetMessageOfDay();
            _errorMessage = errorMessage;
        }

        public IActionResult Index()
        {
  
            var model = new HomeIndexViewModel();
            model.Resturants = _resturantData.GetAll();
            model.CurrentMessage = _greeter;
            return View(model);           
        }

        public IActionResult Details(int id)
        {
            var model = _resturantData.Get(id);
            
            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
            
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ResturantEditModel model)
        {
            if (ModelState.IsValid)
            {
                var newResturant = new Resturant();
                newResturant.Name = model.Name;
                newResturant.Cuisine = model.Cuisine;

                newResturant = _resturantData.Add(newResturant);

                return RedirectToAction(nameof(Details), new { id = newResturant.Id });
            }
            else
            {
                return View();
            }
            
        }
    }
}

OdeToFood/Pages/Greeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Services;

namespace OdeToFood.Pages
{
    public class GreetingModel : PageModel
    {
        private IGreeter _greeter;

        public String CurrentGreeting { get; set; }

        public GreetingModel(IGreeter greeter)
        {
            _greeter = greeter;
        }
        public void OnGet(String name)
        {
            CurrentGreeting = $"{name} : {_greeter.GetMessageOfDay()}";
        }
    }
}

OdeToFood/Pages/Home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Models;
using OdeToFood.Services;

namespace OdeToFood.Pages
{
    public class HomeModel : PageModel
    {
        private IResturantData _resturant;

        public IEnumerable<Resturant> Resturants { get; set; }

        public HomeModel(IResturantData resturant)
        {
            _resturant = resturant;
        }
        public void OnGet()
        {
            
            Resturants = _resturant.GetAll();

        }
    }
}

OdeToFood/ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private IGreeter _greeter;

        public GreeterViewComponent(IGreeter greeter)
        {
            _greeter = greeter;        
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetMessageOfDay();
            return View("Default", model);
        }
    }
}

OdeToFood/Pages/Greeting.cshtml
@page "{name}"

@model GreetingModel
<div>@Model.CurrentGreeting;</div>   

OdeToFood/Pages/Home.cshtml
@page

@model HomeModel

<h1>All resturants</h1>
<table>
    @foreach (var resturant in Model.Resturants)
    {
        <tr>
            <td>@resturant.Id</td>
            <td>@resturant.Name</td>
            <td>
                <a asp-action="Details" asp-route-id="@resturant.Id">More</a>
            </td>

        </tr>
    }
</table>
}

OdeToFood/Pages/Resturants/Edit.cshtml
@page "{id}"
@using OdeToFood.Pages.Resturants

@model EditModel

<h1>Edit @Model.Resturant.Name</h1> 
<form method="post">

    <input type="hidden" asp-for="Resturant.Id"/>   
    <div>
        <label asp-for="Resturant.Name"></label>
        <input asp-for="Resturant.Name" />
        <span asp-validation-for="Resturant.Name"></span>
    </div>
    <div>
        <label asp-for="Resturant.Cuisine"></label>
        <select asp-for="Resturant.Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Resturant.Cuisine"></span>
    </div>
    <input type="submit" name="save" value="Save" />


</form>

OdeToFood/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    
</body>
</html>

OdeToFood/Views/Home/Create.cshtml
@model Resturant

@{ 
    ViewBag.Title = "Create";
}
<h1>Create</h1>
<form method="post">

    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <label asp-for="Cuisine"></label>
        <select asp-for="Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Cuisine"></span>
    </div>
    <input type="submit" name="save" value="Save" />


</form>

OdeToFood/Views/Home/Details.cshtml
@model Resturant

@{
    ViewBag.Title = Model.Name;
}

<h1>@Model.Name</h1>

<div>Id: @Model.Id</div>
<div>Cuisine: @Model.Cuisine </div>
<div> ... Details ...</div>
<a asp-action="Index" asp-controller="Home">Home</a>

OdeToFood/Views/Home/ErrorMessage.cshtml
@model OdeToFood.Models.ErrorMessage

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <h1>@Model.id</h1>
    <h2>@Model.message</h2>
</body>
</html>

OdeToFood/Views/Home/Index.cshtml
@model HomeIndexViewModel

@{
    ViewBag.Title = "Home Page";
}
<h1>All resturants</h1>

@foreach (var resturant in Model.Resturants)
{
    @Html.Partial("_Summery", resturant)

}
<div><a asp-action="Create"> Add resturant</a></div>

OdeToFood/Views/Home/_summery.cshtml
@model Resturant

<section>
    <h3>@Model.Name</h3>
    <div> 
        Cuisine: @Model.Cuisine
    </div>
    <div>
        <a asp-action="Details" asp-route-id="@Model.Id">More</a>
        <a asp-page="/Resturants/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
</section>

OdeToFood/Views/Shared/Components/Greeter/Default.cshtml
@model string

<div>
    @Model
</div>

OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required:false)
        <vc:greeter></vc:greeter>
    </footer>
    
</body>
</html>